// <auto-generated />
using System;
using DentistAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DentistAPI.Migrations
{
    [DbContext(typeof(DentistAPIContext))]
    [Migration("20210208171839_DiagnosisAdded")]
    partial class DiagnosisAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DentistAPI.Models.ClassificationOfDisease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClassificationOfDisease");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "K02",
                            Name = "Zubní kaz"
                        });
                });

            modelBuilder.Entity("DentistAPI.Models.Diagnosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("ClassificationOfDiseaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("ToothId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationOfDiseaseId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("ToothId");

                    b.ToTable("Diagnoses");
                });

            modelBuilder.Entity("DentistAPI.Models.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("ReportText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Encounter");
                });

            modelBuilder.Entity("DentistAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<bool>("Alcohol")
                        .HasColumnType("boolean");

                    b.Property<string>("AlcoholDetail")
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .HasColumnType("text");

                    b.Property<bool>("Drugs")
                        .HasColumnType("boolean");

                    b.Property<bool>("DrugsDetail")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("PersonalAnamnesis")
                        .HasColumnType("text");

                    b.Property<string>("PharmacologicalAnamnesis")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool>("Smoker")
                        .HasColumnType("boolean");

                    b.Property<string>("SmokingDetail")
                        .HasColumnType("text");

                    b.Property<int>("healthInsuranceCompany")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Jabloňová 16 Brno 62100",
                            Age = 28,
                            Alcohol = false,
                            Drugs = false,
                            DrugsDetail = false,
                            Email = "jana.novakova@gmail.com",
                            Name = "Jana Nováková",
                            NationalId = "935617/4905",
                            Phone = "655 475 877",
                            Smoker = false,
                            healthInsuranceCompany = 0
                        });
                });

            modelBuilder.Entity("DentistAPI.Models.Tooth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Deciduous")
                        .HasColumnType("boolean");

                    b.Property<string>("Localization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teeth");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deciduous = false,
                            Localization = "11"
                        },
                        new
                        {
                            Id = 2,
                            Deciduous = false,
                            Localization = "12"
                        },
                        new
                        {
                            Id = 3,
                            Deciduous = false,
                            Localization = "13"
                        },
                        new
                        {
                            Id = 4,
                            Deciduous = false,
                            Localization = "14"
                        },
                        new
                        {
                            Id = 5,
                            Deciduous = false,
                            Localization = "15"
                        },
                        new
                        {
                            Id = 6,
                            Deciduous = false,
                            Localization = "16"
                        },
                        new
                        {
                            Id = 7,
                            Deciduous = false,
                            Localization = "17"
                        },
                        new
                        {
                            Id = 8,
                            Deciduous = false,
                            Localization = "18"
                        },
                        new
                        {
                            Id = 9,
                            Deciduous = false,
                            Localization = "21"
                        },
                        new
                        {
                            Id = 10,
                            Deciduous = false,
                            Localization = "22"
                        },
                        new
                        {
                            Id = 11,
                            Deciduous = false,
                            Localization = "23"
                        },
                        new
                        {
                            Id = 12,
                            Deciduous = false,
                            Localization = "24"
                        },
                        new
                        {
                            Id = 13,
                            Deciduous = false,
                            Localization = "25"
                        },
                        new
                        {
                            Id = 14,
                            Deciduous = false,
                            Localization = "26"
                        },
                        new
                        {
                            Id = 15,
                            Deciduous = false,
                            Localization = "27"
                        },
                        new
                        {
                            Id = 16,
                            Deciduous = false,
                            Localization = "28"
                        },
                        new
                        {
                            Id = 17,
                            Deciduous = false,
                            Localization = "31"
                        },
                        new
                        {
                            Id = 18,
                            Deciduous = false,
                            Localization = "32"
                        },
                        new
                        {
                            Id = 19,
                            Deciduous = false,
                            Localization = "33"
                        },
                        new
                        {
                            Id = 20,
                            Deciduous = false,
                            Localization = "34"
                        },
                        new
                        {
                            Id = 21,
                            Deciduous = false,
                            Localization = "35"
                        },
                        new
                        {
                            Id = 22,
                            Deciduous = false,
                            Localization = "36"
                        },
                        new
                        {
                            Id = 23,
                            Deciduous = false,
                            Localization = "37"
                        },
                        new
                        {
                            Id = 24,
                            Deciduous = false,
                            Localization = "38"
                        },
                        new
                        {
                            Id = 25,
                            Deciduous = false,
                            Localization = "41"
                        },
                        new
                        {
                            Id = 26,
                            Deciduous = false,
                            Localization = "42"
                        },
                        new
                        {
                            Id = 27,
                            Deciduous = false,
                            Localization = "43"
                        },
                        new
                        {
                            Id = 28,
                            Deciduous = false,
                            Localization = "44"
                        },
                        new
                        {
                            Id = 29,
                            Deciduous = false,
                            Localization = "45"
                        },
                        new
                        {
                            Id = 30,
                            Deciduous = false,
                            Localization = "46"
                        },
                        new
                        {
                            Id = 31,
                            Deciduous = false,
                            Localization = "47"
                        },
                        new
                        {
                            Id = 32,
                            Deciduous = false,
                            Localization = "48"
                        });
                });

            modelBuilder.Entity("DentistAPI.Models.ToothRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("ToothId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ToothId");

                    b.ToTable("ToothRecords");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ToothSurfaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Palatinální plocha"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bukální plocha"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Distální plocha"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Meziální plocha"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Okluzní plocha"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Linguální plocua"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Labiální plocha"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Incizální hrana"
                        });
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurfaceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("ToothRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToothSurfaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToothRecordId");

                    b.HasIndex("ToothSurfaceId");

                    b.ToTable("ToothSurfaceRecord");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurfaceRecordDiagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .HasColumnType("integer");

                    b.Property<int>("ToothSurfaceRecordId")
                        .HasColumnType("integer");

                    b.HasKey("DiagnosisId", "ToothSurfaceRecordId");

                    b.HasIndex("ToothSurfaceRecordId");

                    b.ToTable("ToothSurfaceRecordDiagnoses");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothToothSurface", b =>
                {
                    b.Property<int>("ToothId")
                        .HasColumnType("integer");

                    b.Property<int>("SurfaceId")
                        .HasColumnType("integer");

                    b.HasKey("ToothId", "SurfaceId");

                    b.HasIndex("SurfaceId");

                    b.ToTable("ToothToothSurface");

                    b.HasData(
                        new
                        {
                            ToothId = 1,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 1,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 1,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 1,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 1,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 2,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 2,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 2,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 2,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 2,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 3,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 3,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 3,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 3,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 3,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 4,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 4,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 4,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 4,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 4,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 5,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 5,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 5,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 5,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 5,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 6,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 6,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 6,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 6,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 6,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 7,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 7,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 7,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 7,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 7,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 8,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 8,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 8,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 8,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 8,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 9,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 9,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 9,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 9,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 9,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 10,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 10,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 10,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 10,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 10,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 11,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 11,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 11,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 11,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 11,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 12,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 12,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 12,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 12,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 12,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 13,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 13,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 13,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 13,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 13,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 14,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 14,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 14,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 14,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 14,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 15,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 15,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 15,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 15,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 15,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 16,
                            SurfaceId = 1
                        },
                        new
                        {
                            ToothId = 16,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 16,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 16,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 16,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 17,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 17,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 17,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 17,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 17,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 18,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 18,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 18,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 18,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 18,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 19,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 19,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 19,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 19,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 19,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 20,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 20,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 20,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 20,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 20,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 21,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 21,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 21,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 21,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 21,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 22,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 22,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 22,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 22,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 22,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 23,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 23,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 23,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 23,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 23,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 24,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 24,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 24,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 24,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 24,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 25,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 25,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 25,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 25,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 25,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 26,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 26,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 26,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 26,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 26,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 27,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 27,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 27,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 27,
                            SurfaceId = 8
                        },
                        new
                        {
                            ToothId = 27,
                            SurfaceId = 7
                        },
                        new
                        {
                            ToothId = 28,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 28,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 28,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 28,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 28,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 29,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 29,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 29,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 29,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 29,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 30,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 30,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 30,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 30,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 30,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 31,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 31,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 31,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 31,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 31,
                            SurfaceId = 2
                        },
                        new
                        {
                            ToothId = 32,
                            SurfaceId = 6
                        },
                        new
                        {
                            ToothId = 32,
                            SurfaceId = 3
                        },
                        new
                        {
                            ToothId = 32,
                            SurfaceId = 4
                        },
                        new
                        {
                            ToothId = 32,
                            SurfaceId = 5
                        },
                        new
                        {
                            ToothId = 32,
                            SurfaceId = 2
                        });
                });

            modelBuilder.Entity("DentistAPI.Models.Diagnosis", b =>
                {
                    b.HasOne("DentistAPI.Models.ClassificationOfDisease", "ClassificationOfDisease")
                        .WithMany()
                        .HasForeignKey("ClassificationOfDiseaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DentistAPI.Models.Encounter", "Encounter")
                        .WithMany("Diagnoses")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentistAPI.Models.ToothRecord", "Tooth")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ToothId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ClassificationOfDisease");

                    b.Navigation("Encounter");

                    b.Navigation("Tooth");
                });

            modelBuilder.Entity("DentistAPI.Models.Encounter", b =>
                {
                    b.HasOne("DentistAPI.Models.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothRecord", b =>
                {
                    b.HasOne("DentistAPI.Models.Patient", "Patient")
                        .WithMany("ToothRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentistAPI.Models.Tooth", "Tooth")
                        .WithMany()
                        .HasForeignKey("ToothId");

                    b.Navigation("Patient");

                    b.Navigation("Tooth");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurfaceRecord", b =>
                {
                    b.HasOne("DentistAPI.Models.ToothRecord", "ToothRecord")
                        .WithMany("ToothSurfaces")
                        .HasForeignKey("ToothRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DentistAPI.Models.ToothSurface", "ToothSurface")
                        .WithMany()
                        .HasForeignKey("ToothSurfaceId");

                    b.Navigation("ToothRecord");

                    b.Navigation("ToothSurface");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurfaceRecordDiagnosis", b =>
                {
                    b.HasOne("DentistAPI.Models.Diagnosis", "Diagnosis")
                        .WithMany("ToothSurfaces")
                        .HasForeignKey("DiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentistAPI.Models.ToothSurfaceRecord", "ToothSurfaceRecord")
                        .WithMany("Diagnoses")
                        .HasForeignKey("ToothSurfaceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnosis");

                    b.Navigation("ToothSurfaceRecord");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothToothSurface", b =>
                {
                    b.HasOne("DentistAPI.Models.ToothSurface", "Surface")
                        .WithMany("ToothToothSurface")
                        .HasForeignKey("SurfaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentistAPI.Models.Tooth", "Tooth")
                        .WithMany("ToothToothSurface")
                        .HasForeignKey("ToothId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surface");

                    b.Navigation("Tooth");
                });

            modelBuilder.Entity("DentistAPI.Models.Diagnosis", b =>
                {
                    b.Navigation("ToothSurfaces");
                });

            modelBuilder.Entity("DentistAPI.Models.Encounter", b =>
                {
                    b.Navigation("Diagnoses");
                });

            modelBuilder.Entity("DentistAPI.Models.Patient", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("ToothRecords");
                });

            modelBuilder.Entity("DentistAPI.Models.Tooth", b =>
                {
                    b.Navigation("ToothToothSurface");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothRecord", b =>
                {
                    b.Navigation("Diagnoses");

                    b.Navigation("ToothSurfaces");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurface", b =>
                {
                    b.Navigation("ToothToothSurface");
                });

            modelBuilder.Entity("DentistAPI.Models.ToothSurfaceRecord", b =>
                {
                    b.Navigation("Diagnoses");
                });
#pragma warning restore 612, 618
        }
    }
}
